# Generated by Django 2.0.5 on 2019-05-18 15:00

from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenue', django_markdown.models.MarkdownField()),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('publier', models.BooleanField(default=True)),
                ('créé', models.DateTimeField(auto_now_add=True)),
                ('modifié', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
